- docs/xamarin-forms/deploy-test/index.md
Changed Index for `Deployment and Testing`
> Changed Index for `Deployment and Testing`

- docs/tools/live-player/index.md
- docs/tools/live-player/install.md
- docs/tools/live-player/limitations.md
https://github.com/MicrosoftDocs/xamarin-docs.es-es/pull/2
> Wilsonvargas live

- docs/tools/live-player/index.md
- docs/tools/live-player/install.md
- docs/tools/live-player/limitations.md
Changed Index for `Xamarin Live Player for Xamarin.Forms`
> Changed Index for Xamarin Live Player

- docs/tools/live-player/index.md
- docs/tools/live-player/install.md
- docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md
Pull request opened by OPS to resolve syncing conflicts from repo_sync_working_branch to live.
> Resolve syncing conflicts from repo_sync_working_branch to live

- docs/xamarin-forms/app-fundamentals/index.md
https://github.com/MicrosoftDocs/xamarin-docs.es-es/pull/11
> Luisdaviddela patch 2

- docs/xamarin-forms/platform/device.md
https://github.com/MicrosoftDocs/xamarin-docs.es-es/pull/21
> Alejandro ruiz patch 1

- docs/xamarin-forms/platform/device.md
Enhancements in Default Spanish Translated Docs for "Device" Class
> Enhancements for "Device" Class Spanish Docs

- docs/essentials/sms.md
Minor Changes in the default Spanish translated SMS docs for Xamarin.Essentials
> Minor Changes in the SMS docs for Xamarin.Essentials

- docs/cross-platform/macios/unified/overview.md
Se dio una lectura más entendible a la que es traducida automáticamente
> Introducción a la API unificada

- docs/graphics-games/skiasharp/index.md
Se mejoró la traducción del documento que se hace automáticamente
> Dibujo en 2D con SkiaSharp

- docs/essentials/clipboard.md
Minor Changes to the Clipboard class spanish docs
> Minor Changes to Clipboard class docs

- docs/essentials/app-information.md
Minor Changes to the AppInfo class spanish docs
> Minor Changes to AppInfo class docs

- docs/essentials/data-transfer.md
Minor Changes to the DataTransfer class spanish docs
> Minor Changes to DataTransfer class docs

- docs/get-started/index.md
en vez de escribir en este artículo examina... se lee mejor algo así: Este artículo examina los...
> Mala redacción

- docs/get-started/index.md
se lee mejor: así como los... que: así como sobre los... Hasta pudiera llegar a confundir un poco
> Mala estructura en la redacción

- docs/xamarin-forms/app-fundamentals/index.md
> Falta una letra

- docs/android/platform/index.md
pequeños cambios en la redacción
> Corrección de redacción

- docs/cross-platform/desktop/index.md
Cambio de  redacción y pequeño cambio en traducción
> Error en la traduccion y redaccion

- docs/xamarin-forms/data-cloud/search/azure-search.md
corrección en algunas partes de la redacción
> correcciones

- docs/cross-platform/platform/index.md
> Bad translation

- docs/xamarin-forms/data-cloud/storage/azure-storage.md
> Pequeño error de redacción

- docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md
Pequeño cambio en la redacción
> Correcion de redaccion

- docs/xamarin-forms/enterprise-application-patterns/index.md
La palabra extendido, en Introducción
"es importante compilar una aplicación para que se puede modificar o extendido con el tiempo"
podría ser:
"es importante compilar una aplicación para que se puede modificar o extender con el tiempo"
> Palabra mal

- docs/xamarin-forms/enterprise-application-patterns/index.md
Cambio en los conectores entre las palabras
> Corrección de Redacción de texto

- docs/xamarin-forms/enterprise-application-patterns/index.md
Se sustituye una palabra por otra  para mayor claridad
> Cambio de Palabra

- docs/xamarin-forms/user-interface/layouts/bindable-layouts.md
* Corrected content and technical equivalents in Spanish (international audience)
Calling out Xamarin folks to review it
@migueldeicaza @jsuarezruiz
Open to discussion / invite others to review
> Spanish friendly version of Bindable Layouts

- docs/xamarin-forms/user-interface/index.md
Se Cambia La redacción del texto en ciertos parrafos
> Corrección de Conectores y Palabras

- docs/xamarin-forms/enterprise-application-patterns/index.md
"y permite a los desarrolladores y diseñadores de interfaz de usuario más colaboran fácilmente al desarrollar sus respectivos partes de una aplicación."
podría ser:
"y permite a los desarrolladores y diseñadores de interfaz de usuario más colaboraciones fácilmente al desarrollar sus respectivas partes de una aplicación."
> Texto no claro

- docs/xamarin-forms/enterprise-application-patterns/index.md
"Configuración de la aplicación es datos que una aplicación crea"
> No entendible

- docs/xamarin-forms/user-interface/graphics/skiasharp/index.md
Se realizaron unos cambios en la  traducción y redacción, para tener una lectura más clara.
> Corrección de la redacción

- docs/tools/ios-simulator/index.md
Word fixes on iOS Simulator file.
> Words fixes

- docs/xamarin-forms/app-fundamentals/dual-screen/design-patterns.md
Already in the master branch
Información útil para hacer una sugerencia:
1. Vaya a [Quick Start Localization Style Guides (Guías de estilo de localización de inicio rápido)](https://docs.Microsoft.com/Globalization/Localization/styleguides) para comprobar las **diez reglas más importantes** de la guía de estilo de Microsoft.
2. Vaya a [Portal lingüístico de Microsoft](https://www.Microsoft.com/Language) para comprobar la **traducción normalizada de un término** en todos los productos de Microsoft.
> Update link to dual screen GitHub sample project
